import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Spectre",
  description: "Generated by create next app",
}

const RootLayout = ({children}: Readonly<{children: React.ReactNode}>) => {
    return (
        <html lang="en">
            <body>
                <Nav />
                <main id="__root__">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}

export default RootLayout